; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
lib_deps =
   ; infrared remote library 
   ;z3t0/IRremote @ ^3.4.0
   z3t0/IRremote
   ; ansi escape sequence library
   robtillaart/ANSI@^0.3.2
   seeed-studio/Grove - LCD RGB Backlight @ 1.0.2
   smougenot/TM1637 @ 0.0.0-alpha+sha.9486982048
monitor_filters = direct
monitor_speed = 9600
debug_init_break = tbreak setup
upload_protocol = esptool
debug_tool = custom
debug_server =
    ${platformio.packages_dir}/tool-openocd-esp32/bin/openocd
    -s ${platformio.packages_dir}/tool-openocd-esp32/share/openocd/scripts
    -f board/esp32-bridge.cfg
    -c "adapter speed 5000"
build_type = debug
